### ISSUE TITLE
Model fails when only one timeslice [BUG] 

### ISSUE THREAD

**Issue by tsmbland** [EnergySystemsModellingLab/MUSE_OS#446]
## Describe the bug

I get the following error if I try to run a model with only one timeslice:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tbland\AppData\Local\anaconda3\envs\muse_env\Scripts\muse.exe\__main__.py", line 7, in <module>
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\__main__.py", line 61, in run
    muse_main(args.settings, args.model, args.copy)
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\__main__.py", line 56, in muse_main
    MCA.factory(settings).run()
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\mca.py", line 343, in run
    _, new_market, self.sectors = self.find_equilibrium(new_market)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\mca.py", line 208, in find_equilibrium
    return find_equilibrium(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\mca.py", line 545, in find_equilibrium
    market, equilibrium_sectors = single_year_iteration(market, sectors)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\mca.py", line 459, in single_year_iteration
    sector_market = sector.next(
                    ^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\sectors\sector.py", line 231, in next
    subsector.invest(
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\sectors\subsector.py", line 68, in invest
    lp_problem = self.aggregate_lp(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\sectors\subsector.py", line 141, in aggregate_lp
    result = agent.next(
             ^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\agents\agent.py", line 416, in next
    search = super().next(technologies, market, demand, time_period=time_period)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\agents\agent.py", line 281, in next
    decision = self._compute_objective(demand, search_space, technologies, market)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\agents\agent.py", line 293, in _compute_objective
    objectives = self.objectives(self, demand, search_space, technologies, market)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\objectives.py", line 144, in objectives
    obj = objective(agent, demand, search_space, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\registration.py", line 174, in decorated
    result = inner_decorated(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\objectives.py", line 178, in decorated_objective
    result = function(agent, reduced_demand, search_space, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\objectives.py", line 636, in lifetime_levelized_cost_of_energy    
    production = convert_timeslice(production, demand.timeslice, QuantityType.EXTENSIVE)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\Documents\Code\MUSE_OS\src\muse\timeslices.py", line 565, in convert_timeslice
    return (P * x).sum("timeslice").rename(**final_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\AppData\Local\anaconda3\envs\muse_env\Lib\site-packages\xarray\core\dataarray.py", line 2489, in rename
    dataset = self._to_temp_dataset()._rename(name_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\AppData\Local\anaconda3\envs\muse_env\Lib\site-packages\xarray\core\dataset.py", line 4284, in _rename
    variables, coord_names, dims, indexes = self._rename_all(
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\AppData\Local\anaconda3\envs\muse_env\Lib\site-packages\xarray\core\dataset.py", line 4236, in _rename_all
    variables, coord_names = self._rename_vars(name_dict, dims_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbland\AppData\Local\anaconda3\envs\muse_env\Lib\site-packages\xarray\core\dataset.py", line 4196, in _rename_vars
    raise ValueError(f"the new name {name!r} conflicts")
ValueError: the new name 'timeslice' conflicts
```

I'm surprised that nobody has noticed this before, but it does seem like something we should allow. A few of the models I've come across define multiple timeslices with identical parameters/inputs in every timeslice, which does nothing except slow down the simulation and complicate the results.

## Context

Please, complete the following to better understand the system you are using to run MUSE.

- Operating system (eg. Windows 10):
- MUSE version (eg. 1.0.1): dev and 1.1.0
- Installation method (eg. pipx, pip, development mode):
- Python version (you can get this running `python --version`):

**Comment by tsmbland** [comment]
This is now fixed - no problems running models with a single timeslice
